// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWRtmM1SAMHlndI_6QRuRbY2MlidXJBVo',
    appId: '1:161231858044:android:05c0c49eb150d23c09dcf9',
    messagingSenderId: '161231858044',
    projectId: 'brain-hacking-auth',
    storageBucket: 'brain-hacking-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAM0LsBV8PWsOmBMDz3zuSnKdn9Opmp84',
    appId: '1:161231858044:ios:506509e2c1ee28eb09dcf9',
    messagingSenderId: '161231858044',
    projectId: 'brain-hacking-auth',
    storageBucket: 'brain-hacking-auth.appspot.com',
    androidClientId:
        '161231858044-u8e7rjgej1irgn80pp57varc9d4p93hj.apps.googleusercontent.com',
    iosClientId:
        '161231858044-3giqkuh7ipdcandk8lfo67442bd4h5h2.apps.googleusercontent.com',
    iosBundleId: 'com.base.app.check.dev',
  );
}
